## Contenido
1.1. Problema de calidad de los datos.

1.2. Conversiones de datos.

1.3. Filtrado de datos.

1.4. Selección de variables.

## Introducción

![](https://raw.githubusercontent.com/igomezv/CienciaDatosIntermedio/main/img/ML_flow1.png)
Fuente de la imagen: medium.com

## ¿Qué es y por qué es importante el pre-procesamiento?

## ¿Qué problemas pueden tener los datos?

- Datos nulos
- Formatos del archivo, ¿cómo leerlos?
- Tipo de datos incorrectos.

-------

# Problemas en los datos

---------

In [1]:
import numpy as np

In [2]:
lista = [[1,2],[3,4],[5, "na"]]

In [3]:
larray = np.array(lista)

In [4]:
larray * 5

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

#### ¿Por qué nos marca error?

In [5]:
larray, np.shape(larray), type(larray)

(array([['1', '2'],
        ['3', '4'],
        ['5', 'na']], dtype='<U21'),
 (3, 2),
 numpy.ndarray)

#### Investigar dtype=U en https://numpy.org/doc/stable/reference/arrays.dtypes.html 

In [6]:
larray = np.array(lista, dtype=float)

ValueError: could not convert string to float: 'na'

In [7]:
lista[2][1]

'na'

In [8]:
lista[2][1] = np.nan

In [9]:
lista

[[1, 2], [3, 4], [5, nan]]

In [10]:
larray = np.array(lista)

In [11]:
larray, np.shape(larray), type(larray)

(array([[ 1.,  2.],
        [ 3.,  4.],
        [ 5., nan]]),
 (3, 2),
 numpy.ndarray)

In [12]:
larray * 5

array([[ 5., 10.],
       [15., 20.],
       [25., nan]])

 ### Quitar valores nulos con sklearn.preprocessing https://scikit-learn.org/stable/modules/impute.html#impute

In [13]:
from sklearn.impute import SimpleImputer

In [14]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [15]:
imp.fit(larray)

SimpleImputer()

In [16]:
imp.transform(larray)

array([[1., 2.],
       [3., 4.],
       [5., 3.]])

##### Repetir y probar con diferentes estrategias
#### Leer y quitar valores nulos con pandas

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame(lista)

In [19]:
#repasando dataframes de pandas 
# https://www.analyticslane.com/2019/06/21/seleccionar-filas-y-columnas-en-pandas-con-iloc-y-loc/
print(df.iloc[:, 0]) # Primera columna
print(df.iloc[:, 1]) # Segunda columna
df.iloc[:, -1] # Última columna

0    1
1    3
2    5
Name: 0, dtype: int64
0    2.0
1    4.0
2    NaN
Name: 1, dtype: float64


0    2.0
1    4.0
2    NaN
Name: 1, dtype: float64

In [20]:
df.iloc[2]

0    5.0
1    NaN
Name: 2, dtype: float64

In [21]:
df[1]

0    2.0
1    4.0
2    NaN
Name: 1, dtype: float64

In [22]:
df2 = pd.to_numeric(df[1], errors ='coerce')
df2

0    2.0
1    4.0
2    NaN
Name: 1, dtype: float64

In [23]:
df3=df2.dropna(how='all')
df3

0    2.0
1    4.0
Name: 1, dtype: float64

In [24]:
df3=df2.dropna(how='any')
df3

0    2.0
1    4.0
Name: 1, dtype: float64

In [25]:
df2 = pd.to_numeric(df[1], errors ='coerce').fillna(0)#.astype('int')
df2

0    2.0
1    4.0
2    0.0
Name: 1, dtype: float64

In [26]:
df.iloc[:, 1] = df2
df

0    1
0  1  2.0
1  3  4.0
2  5  0.0

## Cargar un archivo de texto

In [27]:
np.loadtxt('datasets/prueba1.csv', skiprows=1, usecols=[4,5,6])

array([[45., 70.,  8.],
       [40., 60.,  7.],
       [44., 55.,  6.],
       [30., 50.,  7.],
       [60., 85.,  9.],
       [55., 65.,  8.],
       [50., 73.,  5.],
       [33., 70.,  8.]])

In [28]:
np.loadtxt('datasets/prueba2.csv', skiprows=1, usecols=[4,5,6]) #, delimiter=',')

IndexError: list index out of range