3.1. Problema de calidad de los datos.
    - NaN, datos faltantes
    - Mayúsculas
    - 

3.2. Conversiones de datos (30 min).

3.3. Filtrado de datos (1 h).

3.4. Selección de variables (30 h).


## ¿Qué problemas pueden tener los datos?

- Datos nulos
- Mayusculas/minúsculas
- Formatos del archivo, ¿cómo leerlos?

In [1]:
import numpy as np

In [6]:
lista = [[1,2],[3,4],[5, "na"]]

In [10]:
larray = np.array(lista)

In [11]:
larray * 5

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [2]:
array_prueba = np.array([[40, np.nan], [20,30],[30,40]])

In [3]:
array_prueba

array([[40., nan],
       [20., 30.],
       [30., 40.]])

### Quitar valores nulos con sklearn.preprocessing

In [5]:
np.shape(array_prueba)

(3, 2)

In [11]:
np.loadtxt('datasets/prueba1.csv', skiprows=1, usecols=[4,5,6])

array([[45., 70.,  8.],
       [40., 60.,  7.],
       [44., 55.,  6.],
       [30., 50.,  7.],
       [60., 85.,  9.],
       [55., 65.,  8.],
       [50., 73.,  5.],
       [33., 70.,  8.]])

In [15]:
np.loadtxt('datasets/prueba2.csv', skiprows=1, usecols=[4,5,6], delimiter=',')

array([[45., 70.,  8.],
       [40., 60.,  7.],
       [44., 55.,  6.],
       [30., 50.,  7.],
       [60., 85.,  9.],
       [55., 65.,  8.],
       [50., 73.,  5.],
       [33., 70.,  8.]])

In [ ]:
sk