3.1. Problema de calidad de los datos.
    - NaN, datos faltantes
    - Mayúsculas
    - 

3.2. Conversiones de datos (30 min).

3.3. Filtrado de datos (1 h).

3.4. Selección de variables (30 h).

(https://d2mk45aasx86xg.cloudfront.net/image10_11zon_6f0d16a388.web[

## ¿Qué es y por qué es importante el pre-procesamiento?


## ¿Qué problemas pueden tener los datos?

- Datos nulos
- Mayusculas/minúsculas
- Formatos del archivo, ¿cómo leerlos?

In [2]:
import numpy as np

In [3]:
lista = [[1,2],[3,4],[5, "na"]]

In [4]:
larray = np.array(lista)

In [5]:
larray * 5

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

#### ¿Por qué nos marca error?

In [9]:
larray, np.shape(larray), type(larray)

(array([['1', '2'],
        ['3', '4'],
        ['5', 'na']], dtype='<U21'),
 (3, 2),
 numpy.ndarray)

#### Investigar dtype=U en https://numpy.org/doc/stable/reference/arrays.dtypes.html 

In [21]:
larray = np.array(lista, dtype=float)

In [22]:
lista[2][1]

nan

In [23]:
lista[2][1] = np.nan

In [24]:
lista

[[1, 2], [3, 4], [5, nan]]

In [25]:
larray = np.array(lista)

In [26]:
larray, np.shape(larray), type(larray)

(array([[ 1.,  2.],
        [ 3.,  4.],
        [ 5., nan]]),
 (3, 2),
 numpy.ndarray)

In [27]:
larray * 5

array([[ 5., 10.],
       [15., 20.],
       [25., nan]])

 ### Quitar valores nulos con sklearn.preprocessing https://scikit-learn.org/stable/modules/impute.html#impute

In [29]:
from sklearn.impute import SimpleImputer

In [30]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')

In [31]:
imp.fit(larray)

SimpleImputer()

In [33]:
imp.transform(larray)

array([[1., 2.],
       [3., 4.],
       [5., 3.]])

##### Repetir y probar con diferentes estrategias

In [11]:
np.loadtxt('datasets/prueba1.csv', skiprows=1, usecols=[4,5,6])

array([[45., 70.,  8.],
       [40., 60.,  7.],
       [44., 55.,  6.],
       [30., 50.,  7.],
       [60., 85.,  9.],
       [55., 65.,  8.],
       [50., 73.,  5.],
       [33., 70.,  8.]])

In [15]:
np.loadtxt('datasets/prueba2.csv', skiprows=1, usecols=[4,5,6], delimiter=',')

array([[45., 70.,  8.],
       [40., 60.,  7.],
       [44., 55.,  6.],
       [30., 50.,  7.],
       [60., 85.,  9.],
       [55., 65.,  8.],
       [50., 73.,  5.],
       [33., 70.,  8.]])

In [ ]:
sk